### Create New User
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "batu2",
    "password": "1234"
}

###Login User
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "batu2",
    "password": "1234"
}
###

GET http://localhost:8080/quest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDczNDcxMDUsImlhdCI6MTc0NzI2MDcwNSwidXNlcm5hbWUiOiJiYXR1MiJ9.ZlVAv7D1EHmUNOdRyOVwwjAC_w1Pkx8Jb_2N0ZGPEbM
